// Portfolio project metadata used by the project list and project details pages.

const Items = [
  {
    id: 1,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775109613/Screenshot_2026-04-01_at_11.53.35_PM_wzrvtd.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775109613/Screenshot_2026-04-01_at_11.53.48_PM_hch842.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775109614/Screenshot_2026-04-01_at_11.54.04_PM_x3msqr.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775109616/Screenshot_2026-04-01_at_11.54.35_PM_dl6k2r.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775109616/Screenshot_2026-04-01_at_11.54.49_PM_sbiq4w.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775109617/Screenshot_2026-04-01_at_11.55.04_PM_wssojg.png",
    ],
    features: [
      "User registration and login",
      "Role-based access control (Admin and User)",
      "Browse and purchase beats",
      "Secure Stripe checkout with embedded payment forms",
      "Profile editing",
      "Contact",
      "Blog system with admin panel",
      "Create/edit/delete Blog Post",
      "Automated email notifications for purchases",
      "Responsive Design",
      "404 Page and many more.",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React icons",
      "Vite",
      "CSS",
      "React Stripe.js",
      "Node.js",
      "Express",
      "MongoDB",
      "Mongoose",
      "JWT",
      "bcryptjs",
      "Nodemailer",
      "AWS Amplify",
    ],
    title: "JustMalikBeats",
    description:
      "A responsive music storefront built for an independent producer to showcase beats, preview tracks, and move visitors through a clear purchase flow. The focus was a polished frontend experience, strong brand presentation, and a smoother path from discovery to checkout.",
    category: "business",
    liveLink: "https://malikbeats.com/",
    codeLink: "https://github.com/ZacksBroDev/JustMalikBeats",
  },
  {
    id: 2,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106075/Screenshot_2026-04-01_at_10.38.11_PM_fg5yeh.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106077/Screenshot_2026-04-01_at_10.39.17_PM_mypy7m.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106075/Screenshot_2026-04-01_at_10.38.11_PM_fg5yeh.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106075/Screenshot_2026-04-01_at_10.38.23_PM_wcrlxl.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106075/Screenshot_2026-04-01_at_10.38.33_PM_hmouhg.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106076/Screenshot_2026-04-01_at_10.38.46_PM_d6bhms.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106076/Screenshot_2026-04-01_at_10.38.56_PM_ghvk4w.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106077/Screenshot_2026-04-01_at_10.39.05_PM_hunenv.png",
    ],
    features: [
      "User registration and login",
      "Authentication using JWT Tokens",
      "Role-based access control (Admin and User)",
      "Admin Dashboard",
      "Real-time participant tracking",
      "Responsive Design",
      "Web3Forms",
      "Delete users",
      "Create new access codes",
      "Create new events",
      "404 Page and many more.",
    ],
    technologies: [
      "React",
      "React DOM",
      "React Hooks",
      "React Icons",
      "Vite",
      "CSS",
      "NodeJS",
      "Json Web Token",
      "AWS Amplify",
      "Docker",
    ],
    title: "MHKTraining",
    description:
      "A centralized training platform designed to make lessons, schedules, videos, and resources easy to navigate across desktop and mobile. The product emphasizes clear information architecture, responsive layouts, and a low-friction student experience.",
    category: "business",
    liveLink: "https://mhktraining.com/",
    codeLink: "https://github.com/ZacksBroDev/MHKWebsite",
  },
  {
    id: 3,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106051/Screenshot_2026-04-01_at_10.35.22_PM_c2gmbr.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106051/Screenshot_2026-04-01_at_10.35.22_PM_c2gmbr.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106051/Screenshot_2026-04-01_at_10.35.40_PM_paue1h.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106051/Screenshot_2026-04-01_at_10.35.53_PM_ahzr73.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106052/Screenshot_2026-04-01_at_10.36.05_PM_q3wjra.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106056/Screenshot_2026-04-01_at_10.36.17_PM_hge81q.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106052/Screenshot_2026-04-01_at_10.36.27_PM_sfel2e.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106052/Screenshot_2026-04-01_at_10.36.38_PM_gwon33.png",
    ],
    features: [
      "User registration and login",
      "Leave a Reviews",
      "Skeleton loading effect",
      "Responsive Design",
      "Schedules & Booking",
      "Photo Gallery",
      "Web3Forms React",
      "Latest Releases",
    ],
    technologies: ["HTML", "CSS", "JavaScript", "Cloudinary"],
    title: "The Futons",
    description:
      "A clean, high-impact promotional website built to elevate a small band's online presence showcasing their music, brand, and identity in one centralized hub. Designed for discoverability, fast performance, and fan engagement, the site helps the band look legitimate, memorable, and easy to find.",
    category: "business",
    liveLink: "https://thefutons.band/",
    codeLink: "https://github.com/ZacksBroDev/TheFutons",
  },

  {
    id: 4,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767162303/Screenshot_2025-12-30_at_11.21.50_PM_rfrtgc.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767162303/Screenshot_2025-12-30_at_11.21.50_PM_rfrtgc.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767162306/Screenshot_2025-12-30_at_11.22.11_PM_jpfl80.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767162295/Screenshot_2025-12-30_at_11.22.20_PM_xoa5mz.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767162297/Screenshot_2025-12-30_at_11.22.49_PM_jnwwml.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767162302/Screenshot_2025-12-30_at_11.23.11_PM_qiiavu.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767162300/Screenshot_2025-12-30_at_11.23.25_PM_h1qrhd.png",
    ],
    features: [
      "Session-based authentication with rate limiting and Argon2id hashing",
      "Dashboard with monthly summaries, spending trends, and cashflow charts",
      "Top merchants and subscription detection",
      "CSV import with search, filter, paginate, and inline editing",
      "Merchant mapping with auto-linked aliases and retroactive application",
      "Hierarchical categories with parent/child, colors, icons, and income/expense toggle",
      "Monthly budgets with planned vs. actual comparison and progress bars",
      "Savings goals with target amounts, deadlines, and contribution tracking",
      "Recurring bills with weekly/bi-weekly/monthly/quarterly/yearly schedules",
      "Due date calculation with overdue/due-soon status and reminders",
      "Rules engine with conditions (regex, amount range, direction) and actions",
      "SHA-256 data deduplication for transactions and CSV checksums",
      "Responsive Design",
    ],
    technologies: [
      "Next.js 14",
      "React 18",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "Tailwind CSS",
      "ECharts",
      "Zod",
      "Argon2",
      "PapaParse",
    ],
    title: "My Personal Accountant",
    description:
      "A full-featured personal finance platform built with Next.js and PostgreSQL for logging, categorizing, and analyzing income and expenses. Includes dashboard analytics, merchant mapping, hierarchical budgets, savings goals, recurring bill tracking, an automation rules engine, and SHA-256 deduplication — all behind session-based auth with Argon2id hashing and rate limiting.",
    category: "personal",
    codeLink: "https://github.com/ZacksBroDev/PersonalFinance",
  },
  {
    id: 5,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767161121/Screenshot_2025-12-30_at_11.04.37_PM_vmmz3u.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767161121/Screenshot_2025-12-30_at_11.04.37_PM_vmmz3u.png",
    ],
    features: [
      "Multiplayer",
      "Score Board",
      "CRUD for keeping track of progress long term",
    ],
    technologies: ["python"],
    title: "Pong",
    description:
      "Play retro style pong game with smooth animations and a live scoreboard",
    category: "game",
    codeLink: "https://github.com/ZacksBroDev/PersonalFinance",
  },
  {
    id: 6,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651756/Screenshot_2026-03-25_at_8.18.29_AM_fvjfyy.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651755/Screenshot_2026-03-25_at_8.19.11_AM_o9jw6k.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651754/Screenshot_2026-03-25_at_8.18.47_AM_gf9jzr.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651752/Screenshot_2026-03-25_at_8.18.58_AM_p5gpcr.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651752/Screenshot_2026-03-25_at_8.19.28_AM_bnzyge.png",
    ],
    features: [
      "Compliment card deck with 257+ cards",
      "Voucher inventory and request/status workflows",
      "5 voucher templates with reuse prevention",
      "CRUD console managing 263 typed content items",
      "Category-based card filtering (Stressed, Need a laugh, etc.)",
      "Favorites and notes system",
      "Draw and love streaks tracking",
      "Love Meter progress system",
      "4 unlockable themes (Blush, Lavender, Night, Sunset)",
      "Stats dashboard with deck progress",
      "Daily Mode and No Repeat settings",
      "Responsive Design",
    ],
    technologies: ["React", "Vite", "CSS", "LocalStorage"],
    title: "Keepsake Deck",
    description:
      "A gift-based web application with a compliment card deck, voucher inventory, and request/status workflows. Features 257+ personalized cards across multiple categories, redeemable vouchers with rarity tiers, streak tracking, and unlockable themes — all designed as a heartfelt, interactive gift.",
    category: "personal",
    codeLink: "https://github.com/ZacksBroDev/Valentines",
  },
  {
    id: 7,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651690/Screenshot_2026-03-25_at_8.18.11_AM_qke5td.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651690/Screenshot_2026-03-25_at_8.18.11_AM_qke5td.png",
    ],
    features: [
      "Hit, Stand, Double, and Split decision evaluation",
      "First-decision grading against basic strategy",
      "Accuracy and streak tracking",
      "Card Counting (Hi-Lo) with running/true count",
      "Coach Mode",
      "6-deck shoe simulation",
      "Persistent stats in local storage",
      "Responsive Design",
    ],
    technologies: ["HTML", "CSS", "JavaScript"],
    title: "Blackjack First-Decision Coach",
    description:
      "A browser-based blackjack trainer that evaluates Hit, Stand, Double, and Split decisions against basic strategy. Features Hi-Lo card counting, coach mode, accuracy tracking, and streak stats — all stored in local storage for long-term progress.",
    category: "game",
    liveLink: "https://black-jack-nine-fawn.vercel.app/",
    codeLink: "https://github.com/ZacksBroDev/BlackJack",
  },
  {
    id: 8,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651680/Screenshot_2026-03-25_at_8.17.59_AM_qcenez.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651680/Screenshot_2026-03-25_at_8.17.59_AM_qcenez.png",
    ],
    features: [
      "Monte Carlo bankroll simulation",
      "Configurable starting bankroll and bet size",
      "Multiple bet types (Red/Black, etc.)",
      "Max spins and goal amount settings",
      "Bankroll curve visualization",
      "Ending-distribution histogram",
      "Performance analytics dashboard",
      "Canvas API rendering",
      "Responsive Design",
    ],
    technologies: ["HTML", "CSS", "JavaScript", "Canvas API"],
    title: "Roulette Risk Lab",
    description:
      "A Monte Carlo roulette simulator that models bankroll variance across wheel and bet types. Visualizes outcomes with a bankroll curve and ending-distribution histogram, helping users understand risk and probability through interactive simulations.",
    category: "game",
    liveLink: "https://roulette-risk.vercel.app/",
    codeLink: "https://github.com/ZacksBroDev/RouletteRisk",
  },
];

export default Items;
