// Portfolio project metadata used by the project list and project details pages.

const Items = [
  {
    id: 1,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775109613/Screenshot_2026-04-01_at_11.53.35_PM_wzrvtd.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775109613/Screenshot_2026-04-01_at_11.53.48_PM_hch842.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775109614/Screenshot_2026-04-01_at_11.54.04_PM_x3msqr.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775109616/Screenshot_2026-04-01_at_11.54.35_PM_dl6k2r.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775109616/Screenshot_2026-04-01_at_11.54.49_PM_sbiq4w.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775109617/Screenshot_2026-04-01_at_11.55.04_PM_wssojg.png",
    ],
    features: [
      "User registration and login",
      "Role-based access control (Admin and User)",
      "Browse and purchase beats",
      "Secure Stripe checkout with embedded payment forms",
      "Profile editing",
      "Contact",
      "Blog system with admin panel",
      "Create/edit/delete Blog Post",
      "Automated email notifications for purchases",
      "Responsive Design",
      "404 Page and many more.",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React icons",
      "Vite",
      "CSS",
      "React Stripe.js",
      "Node.js",
      "Express",
      "MongoDB",
      "Mongoose",
      "JWT",
      "bcryptjs",
      "Nodemailer",
      "AWS Amplify",
    ],
    title: "JustMalikBeats",
    description:
      "A responsive music storefront built for an independent producer to showcase beats, preview tracks, and move visitors through a clear purchase flow. The focus was a polished frontend experience, strong brand presentation, and a smoother path from discovery to checkout.",
    category: "business",
    liveLink: "https://malikbeats.com/",
    codeLink: "https://github.com/zackaryzbrown/JustMalikBeats",
  },
  {
    id: 2,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106075/Screenshot_2026-04-01_at_10.38.11_PM_fg5yeh.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106077/Screenshot_2026-04-01_at_10.39.17_PM_mypy7m.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106075/Screenshot_2026-04-01_at_10.38.11_PM_fg5yeh.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106075/Screenshot_2026-04-01_at_10.38.23_PM_wcrlxl.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106075/Screenshot_2026-04-01_at_10.38.33_PM_hmouhg.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106076/Screenshot_2026-04-01_at_10.38.46_PM_d6bhms.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106076/Screenshot_2026-04-01_at_10.38.56_PM_ghvk4w.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106077/Screenshot_2026-04-01_at_10.39.05_PM_hunenv.png",
    ],
    features: [
      "User registration and login",
      "Authentication using JWT Tokens",
      "Role-based access control (Admin and User)",
      "Admin Dashboard",
      "Real-time participant tracking",
      "Responsive Design",
      "Web3Forms",
      "Delete users",
      "Create new access codes",
      "Create new events",
      "404 Page and many more.",
    ],
    technologies: [
      "React",
      "React DOM",
      "React Hooks",
      "React Icons",
      "Vite",
      "CSS",
      "NodeJS",
      "Json Web Token",
      "AWS Amplify",
      "Docker",
    ],
    title: "MHKTraining",
    description:
      "A centralized training platform designed to make lessons, schedules, videos, and resources easy to navigate across desktop and mobile. The product emphasizes clear information architecture, responsive layouts, and a low-friction student experience.",
    category: "business",
    liveLink: "https://mhktraining.com/",
    codeLink: "https://github.com/zackaryzbrown/MHKWebsite",
  },
  {
    id: 3,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106051/Screenshot_2026-04-01_at_10.35.22_PM_c2gmbr.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106051/Screenshot_2026-04-01_at_10.35.22_PM_c2gmbr.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106051/Screenshot_2026-04-01_at_10.35.40_PM_paue1h.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106051/Screenshot_2026-04-01_at_10.35.53_PM_ahzr73.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106052/Screenshot_2026-04-01_at_10.36.05_PM_q3wjra.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106056/Screenshot_2026-04-01_at_10.36.17_PM_hge81q.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106052/Screenshot_2026-04-01_at_10.36.27_PM_sfel2e.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/q_auto/f_auto/v1775106052/Screenshot_2026-04-01_at_10.36.38_PM_gwon33.png",
    ],
    features: [
      "User registration and login",
      "Leave a Reviews",
      "Skeleton loading effect",
      "Responsive Design",
      "Schedules & Booking",
      "Photo Gallery",
      "Web3Forms React",
      "Latest Releases",
    ],
    technologies: ["HTML", "CSS", "JavaScript", "Cloudinary"],
    title: "The Futons",
    description:
      "A clean, high-impact promotional website built to elevate a small band's online presence showcasing their music, brand, and identity in one centralized hub. Designed for discoverability, fast performance, and fan engagement, the site helps the band look legitimate, memorable, and easy to find.",
    category: "business",
    liveLink: "https://thefutons.band/",
    codeLink: "https://github.com/zackaryzbrown/TheFutons",
  },

  {
    id: 4,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767162303/Screenshot_2025-12-30_at_11.21.50_PM_rfrtgc.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767162303/Screenshot_2025-12-30_at_11.21.50_PM_rfrtgc.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767162306/Screenshot_2025-12-30_at_11.22.11_PM_jpfl80.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767162295/Screenshot_2025-12-30_at_11.22.20_PM_xoa5mz.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767162297/Screenshot_2025-12-30_at_11.22.49_PM_jnwwml.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767162302/Screenshot_2025-12-30_at_11.23.11_PM_qiiavu.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767162300/Screenshot_2025-12-30_at_11.23.25_PM_h1qrhd.png",
    ],
    features: [
      "Session-based authentication with rate limiting and Argon2id hashing",
      "Dashboard with monthly summaries, spending trends, and cashflow charts",
      "Top merchants and subscription detection",
      "CSV import with search, filter, paginate, and inline editing",
      "Merchant mapping with auto-linked aliases and retroactive application",
      "Hierarchical categories with parent/child, colors, icons, and income/expense toggle",
      "Monthly budgets with planned vs. actual comparison and progress bars",
      "Savings goals with target amounts, deadlines, and contribution tracking",
      "Recurring bills with weekly/bi-weekly/monthly/quarterly/yearly schedules",
      "Due date calculation with overdue/due-soon status and reminders",
      "Rules engine with conditions (regex, amount range, direction) and actions",
      "SHA-256 data deduplication for transactions and CSV checksums",
      "Responsive Design",
    ],
    technologies: [
      "Next.js 14",
      "React 18",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "Tailwind CSS",
      "ECharts",
      "Zod",
      "Argon2",
      "PapaParse",
    ],
    title: "My Personal Accountant",
    description:
      "A full-featured personal finance platform built with Next.js and PostgreSQL for logging, categorizing, and analyzing income and expenses. Includes dashboard analytics, merchant mapping, hierarchical budgets, savings goals, recurring bill tracking, an automation rules engine, and SHA-256 deduplication — all behind session-based auth with Argon2id hashing and rate limiting.",
    category: "personal",
    codeLink: "https://github.com/zackaryzbrown/PersonalFinance",
  },
  {
    id: 5,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767161121/Screenshot_2025-12-30_at_11.04.37_PM_vmmz3u.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1767161121/Screenshot_2025-12-30_at_11.04.37_PM_vmmz3u.png",
    ],
    features: [
      "Multiplayer",
      "Score Board",
      "CRUD for keeping track of progress long term",
    ],
    technologies: ["python"],
    title: "Pong",
    description:
      "Play retro style pong game with smooth animations and a live scoreboard",
    category: "game",
    codeLink: "https://github.com/zackaryzbrown/PersonalFinance",
  },
  {
    id: 6,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651756/Screenshot_2026-03-25_at_8.18.29_AM_fvjfyy.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651755/Screenshot_2026-03-25_at_8.19.11_AM_o9jw6k.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651754/Screenshot_2026-03-25_at_8.18.47_AM_gf9jzr.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651752/Screenshot_2026-03-25_at_8.18.58_AM_p5gpcr.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651752/Screenshot_2026-03-25_at_8.19.28_AM_bnzyge.png",
    ],
    features: [
      "Compliment card deck with 257+ cards",
      "Voucher inventory and request/status workflows",
      "5 voucher templates with reuse prevention",
      "CRUD console managing 263 typed content items",
      "Category-based card filtering (Stressed, Need a laugh, etc.)",
      "Favorites and notes system",
      "Draw and love streaks tracking",
      "Love Meter progress system",
      "4 unlockable themes (Blush, Lavender, Night, Sunset)",
      "Stats dashboard with deck progress",
      "Daily Mode and No Repeat settings",
      "Responsive Design",
    ],
    technologies: ["React", "Vite", "CSS", "LocalStorage"],
    title: "Keepsake Deck",
    description:
      "A gift-based web application with a compliment card deck, voucher inventory, and request/status workflows. Features 257+ personalized cards across multiple categories, redeemable vouchers with rarity tiers, streak tracking, and unlockable themes — all designed as a heartfelt, interactive gift.",
    category: "personal",
    codeLink: "https://github.com/zackaryzbrown/Valentines",
  },
  {
    id: 7,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651690/Screenshot_2026-03-25_at_8.18.11_AM_qke5td.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651690/Screenshot_2026-03-25_at_8.18.11_AM_qke5td.png",
    ],
    features: [
      "Hit, Stand, Double, and Split decision evaluation",
      "First-decision grading against basic strategy",
      "Accuracy and streak tracking",
      "Card Counting (Hi-Lo) with running/true count",
      "Coach Mode",
      "6-deck shoe simulation",
      "Persistent stats in local storage",
      "Responsive Design",
    ],
    technologies: ["HTML", "CSS", "JavaScript"],
    title: "Blackjack First-Decision Coach",
    description:
      "A browser-based blackjack trainer that evaluates Hit, Stand, Double, and Split decisions against basic strategy. Features Hi-Lo card counting, coach mode, accuracy tracking, and streak stats — all stored in local storage for long-term progress.",
    category: "game",
    liveLink: "https://black-jack-nine-fawn.vercel.app/",
    codeLink: "https://github.com/zackaryzbrown/BlackJack",
  },
  {
    id: 8,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651680/Screenshot_2026-03-25_at_8.17.59_AM_qcenez.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1774651680/Screenshot_2026-03-25_at_8.17.59_AM_qcenez.png",
    ],
    features: [
      "Monte Carlo bankroll simulation",
      "Configurable starting bankroll and bet size",
      "Multiple bet types (Red/Black, etc.)",
      "Max spins and goal amount settings",
      "Bankroll curve visualization",
      "Ending-distribution histogram",
      "Performance analytics dashboard",
      "Canvas API rendering",
      "Responsive Design",
    ],
    technologies: ["HTML", "CSS", "JavaScript", "Canvas API"],
    title: "Roulette Risk Lab",
    description:
      "A Monte Carlo roulette simulator that models bankroll variance across wheel and bet types. Visualizes outcomes with a bankroll curve and ending-distribution histogram, helping users understand risk and probability through interactive simulations.",
    category: "game",
    liveLink: "https://roulette-risk.vercel.app/",
    codeLink: "https://github.com/zackaryzbrown/RouletteRisk",
  },
  {
    id: 9,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812675/Screenshot_2026-06-07_at_12.11.09_AM_de1jnz.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812675/Screenshot_2026-06-07_at_12.11.09_AM_de1jnz.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812756/Screenshot_2026-06-07_at_12.12.30_AM_i58tbh.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812797/Screenshot_2026-06-07_at_12.13.11_AM_x1gz4e.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812821/Screenshot_2026-06-07_at_12.13.36_AM_qrxcal.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812844/Screenshot_2026-06-07_at_12.13.57_AM_feenkn.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812869/Screenshot_2026-06-07_at_12.14.22_AM_r8cdlf.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812896/Screenshot_2026-06-07_at_12.14.51_AM_abafhl.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812937/Screenshot_2026-06-07_at_12.15.29_AM_wy8jim.png",
    ],
    features: [
      "Interactive before/after image comparison components",
      "Multi-step form with validation and progress tracking",
      "Google Maps API integration for service area visualization",
      "Dynamic testimonial carousel with star ratings",
      "SMS API integration for instant quote requests",
      "Mobile-first responsive design with touch-optimized UI",
      "Framer Motion animations for smooth transitions",
      "TypeScript for type-safe development",
    ],
    technologies: [
      "React",
      "TypeScript",
      "Vite",
      "Tailwind CSS",
      "Radix UI",
      "MUI",
      "shader/ui",
      "Framer Motion",
    ],
    title: "Mobile Detailing",
    description:
      "Built a high-conversion React/TypeScript SPA with Vite, featuring interactive image comparisons, multi-step forms with real-time validation, and Google Maps integration. Implemented SMS API connectivity for instant quote requests, designed mobile-first with Tailwind CSS and Radix UI, and added fluid animations using Framer Motion — showcasing modern frontend architecture and API integration skills.",
    category: "business",
    liveLink: "https://mobile-details-demo.zackarybrown.net/",
    codeLink: "https://github.com/zackaryzbrown/Mobile-Details",
  },
  {
    id: 10,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812061/Screenshot_2026-06-07_at_12.00.56_AM_hzmkwk.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812061/Screenshot_2026-06-07_at_12.00.56_AM_hzmkwk.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812128/Screenshot_2026-06-07_at_12.02.03_AM_kspxk4.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779347566/Screenshot_2026-05-21_at_1.08.57_AM_nphtu0.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812199/Screenshot_2026-06-07_at_12.03.14_AM_aualon.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812236/Screenshot_2026-06-07_at_12.03.51_AM_ef8ui6.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779347631/Screenshot_2026-05-21_at_1.09.20_AM_jngtzn.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812282/Screenshot_2026-06-07_at_12.04.36_AM_mpioh0.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812305/Screenshot_2026-06-07_at_12.05.00_AM_tzzxbn.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812345/Screenshot_2026-06-07_at_12.05.39_AM_j4lctw.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812376/Screenshot_2026-06-07_at_12.06.10_AM_lgmhxt.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812404/Screenshot_2026-06-07_at_12.06.37_AM_p3xlur.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812473/Screenshot_2026-06-07_at_12.07.48_AM_dxqi2z.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812523/Screenshot_2026-06-07_at_12.08.38_AM_ihgel5.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812546/Screenshot_2026-06-07_at_12.09.00_AM_ixyghj.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812576/Screenshot_2026-06-07_at_12.09.31_AM_qkouv7.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812602/Screenshot_2026-06-07_at_12.09.57_AM_j8xxjz.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780812630/Screenshot_2026-06-07_at_12.10.23_AM_dr1noq.png",
    ],
    features: [
      "Multi-step patient intake form with validation",
      "Interactive service information architecture",
      "Accessibility-compliant UI (WCAG 2.1 AA)",
      "Google Fonts optimization for performance",
      "Form state management with JavaScript",
      "CSS Grid and Flexbox layouts",
      "Mobile-responsive design system",
    ],
    technologies: ["HTML5", "CSS3", "JavaScript", "Google Fonts"],
    title: "North Peak Dental",
    description:
      "Developed an accessible, standards-compliant website with a multi-step patient intake system and form validation using vanilla JavaScript. Architected a clean information hierarchy with CSS Grid/Flexbox layouts, ensured WCAG 2.1 AA accessibility compliance, and optimized font loading for performance — highlighting strong fundamentals in semantic HTML, CSS, and JavaScript.",
    category: "business",
    liveLink: "https://northpeakdental.netlify.app/",
    codeLink: "https://github.com/zackaryzbrown/Dental-Demo",
  },
  {
    id: 11,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811705/Screenshot_2026-06-06_at_11.55.00_PM_hjfnrr.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811705/Screenshot_2026-06-06_at_11.55.00_PM_hjfnrr.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811720/Screenshot_2026-06-06_at_11.55.15_PM_jl3zft.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811734/Screenshot_2026-06-06_at_11.55.29_PM_t1ecey.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811765/Screenshot_2026-06-06_at_11.55.52_PM_ffjid0.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811765/Screenshot_2026-06-06_at_11.55.52_PM_ffjid0.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811773/Screenshot_2026-06-06_at_11.56.09_PM_wuojie.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811799/Screenshot_2026-06-06_at_11.56.24_PM_ysgmmh.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811814/Screenshot_2026-06-06_at_11.56.36_PM_vqf2wt.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811859/Screenshot_2026-06-06_at_11.57.16_PM_nut4hz.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811838/Screenshot_2026-06-06_at_11.57.00_PM_mysq59.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811861/Screenshot_2026-06-06_at_11.57.37_PM_kqsfoz.png",
    ],
    features: [
      "Custom WordPress theme with modular components",
      "Dynamic service catalog with filtering",
      "Rental inventory management system",
      "Customer review aggregation with rating display",
      "Contact form with anti-spam validation",
      "Optimized hero images with WebP format",
      "Mobile-responsive navigation system",
    ],
    technologies: ["WordPress", "PHP", "JavaScript", "CSS"],
    title: "Trailhead Cycles",
    description:
      "Built a custom WordPress solution with dynamic service catalogs and a rental inventory management system. Developed modular PHP components for scalability, implemented customer review aggregation with rating displays, and optimized image delivery using WebP format. Created a responsive navigation system — demonstrating WordPress customization and content management expertise.",
    category: "business",
    liveLink: "https://zackaryzbrown-yeswj.wordpress.com/",
  },
  {
    id: 12,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811345/Screenshot_2026-06-06_at_11.49.01_PM_kqwvmx.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811345/Screenshot_2026-06-06_at_11.49.01_PM_kqwvmx.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811394/Screenshot_2026-06-06_at_11.49.44_PM_qmgvdr.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779347164/Screenshot_2026-05-21_at_1.04.14_AM_kwzk4n.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811472/Screenshot_2026-06-06_at_11.51.07_PM_csio1a.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811529/Screenshot_2026-06-06_at_11.52.03_PM_l9pybg.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811557/Screenshot_2026-06-06_at_11.52.33_PM_f5ocbw.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811576/Screenshot_2026-06-06_at_11.52.52_PM_iv5qhl.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779347164/Screenshot_2026-05-21_at_1.05.14_AM_mezt0i.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1780811500/Screenshot_2026-06-06_at_11.51.33_PM_ijtnbl.png",
    ],
    features: [
      "Interactive pricing comparison table with JavaScript",
      "Responsive feature grid with CSS Grid",
      "Dynamic testimonial slider with autoplay",
      "Semantic HTML5 structure for SEO",
      "CSS custom properties for theming",
      "Form validation with real-time feedback",
      "Performance-optimized with minimal dependencies",
    ],
    technologies: ["HTML5", "CSS3", "JavaScript"],
    title: "Floor Hosting",
    description:
      "Developed a performance-focused landing page using vanilla JavaScript, featuring an interactive pricing comparison table and dynamic content. Utilized CSS Grid for responsive layouts, CSS custom properties for theming, and semantic HTML5 for SEO optimization. Implemented real-time form validation without frameworks — showcasing ability to build efficient, performant sites with core web technologies.",
    category: "business",
    liveLink: "https://stupendous-otter-759661.netlify.app/",
    codeLink: "https://github.com/zackaryzbrown/floor-hosting",
  },
  {
    id: 13,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346911/Screenshot_2026-05-21_at_12.59.50_AM_cjyafj.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346911/Screenshot_2026-05-21_at_12.59.50_AM_cjyafj.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346915/Screenshot_2026-05-21_at_1.00.00_AM_a8mwto.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346918/Screenshot_2026-05-21_at_1.00.14_AM_jldh43.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346915/Screenshot_2026-05-21_at_1.00.26_AM_gmcmvs.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346916/Screenshot_2026-05-21_at_1.00.34_AM_iqcx3o.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346917/Screenshot_2026-05-21_at_1.00.52_AM_zbyxcb.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346919/Screenshot_2026-05-21_at_1.01.06_AM_yfuptj.png",
    ],
    features: [
      "Type-safe React components with TypeScript",
      "React Hook Form with Zod schema validation",
      "Reusable component library with Radix UI primitives",
      "Animated transitions with Framer Motion",
      "Responsive design system with Tailwind CSS",
      "Form state management and error handling",
      "Performance optimization with code splitting",
    ],
    technologies: [
      "React",
      "TypeScript",
      "Vite",
      "Tailwind CSS",
      "Radix UI",
      "shader/ui",
      "Framer Motion",
      "React Hook Form",
      "Zod",
    ],
    title: "Mobile Auto Detailing",
    description:
      "Engineered a type-safe React/TypeScript application with Vite, implementing React Hook Form with Zod schema validation for robust form handling. Built a reusable component library using Radix UI primitives and Tailwind CSS, integrated Framer Motion for smooth animations, and optimized bundle size with code splitting — demonstrating modern React development practices and TypeScript proficiency.",
    category: "business",
    liveLink: "https://zekie-demo.zackarybrown.net/",
    codeLink: "https://github.com/zackaryzbrown/Zekie-Detailing",
  },
  {
    id: 14,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779348370/Screenshot_2026-05-21_at_1.17.32_AM_asildh.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779348370/Screenshot_2026-05-21_at_1.17.32_AM_asildh.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779348381/Screenshot_2026-05-21_at_1.17.44_AM_pvpfo4.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779348380/Screenshot_2026-05-21_at_1.17.54_AM_hc7tva.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779348381/Screenshot_2026-05-21_at_1.18.20_AM_ecvu0f.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779348380/Screenshot_2026-05-21_at_1.18.33_AM_jjug3v.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779348380/Screenshot_2026-05-21_at_1.18.42_AM_skpduk.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779348380/Screenshot_2026-05-21_at_1.18.53_AM_fx26yg.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779348380/Screenshot_2026-05-21_at_1.18.02_AM_uqjohb.png",
    ],
    features: [
      "Pet photo contest platform with voting system",
      "Server actions for secure full-stack data workflows",
      "Webhook-driven donation processing with HMAC-SHA256 verification",
      "Admin moderation and reconciliation tools",
      "Donation-to-vote mapping and reconciliation flows",
      "Row Level Security (RLS) policies",
      "SQL migrations, views, triggers, and helper functions",
      "Pledge.to payment integration",
      "Supabase Auth and Storage integration",
      "Vercel Analytics and Speed Insights",
      "Environment-based production build config",
      "Seed and webhook simulation scripts for local testing",
      "Responsive Design",
    ],
    technologies: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Tailwind CSS",
      "Radix UI",
      "class-variance-authority",
      "clsx",
      "tailwind-merge",
      "Lucide React",
      "Supabase",
      "PostgreSQL",
      "@supabase/supabase-js",
      "@supabase/ssr",
      "Zod",
      "Node.js",
      "Pledge.to",
      "AWS Amplify",
      "Vercel Analytics",
      "ESLint 9",
      "PostCSS",
    ],
    title: "Cutepet Showdown",
    description:
      "A production-ready pet photo contest platform using Next.js 15, React 19, and TypeScript, with Supabase (PostgreSQL, Auth, Storage, and RLS) powering secure full-stack data workflows. Implemented server actions, webhook-driven donation processing with HMAC verification (Pledge.to), and admin moderation/reconciliation tools. Styled with Tailwind CSS and Radix UI, deployed via AWS Amplify, and instrumented with Vercel Analytics and Speed Insights for performance and usage monitoring.",
    category: "business",
    liveLink: "https://cutepetshowdown.com",
    codeLink: "https://github.com/zackaryzbrown/LiamsPetProject",
  },
  {
    id: 15,
    mainImage:
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346688/Screenshot_2026-05-21_at_12.53.55_AM_fgxunu.png",
    img: [
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346688/Screenshot_2026-05-21_at_12.53.55_AM_fgxunu.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346699/Screenshot_2026-05-21_at_12.54.06_AM_lc09sm.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346698/Screenshot_2026-05-21_at_12.54.27_AM_wjx1ag.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346700/Screenshot_2026-05-21_at_12.54.38_AM_ycad9j.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346700/Screenshot_2026-05-21_at_12.54.38_AM_ycad9j.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346696/Screenshot_2026-05-21_at_12.54.16_AM_mi6cli.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346704/Screenshot_2026-05-21_at_12.56.21_AM_yrgder.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346707/Screenshot_2026-05-21_at_12.56.28_AM_ijoy3u.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346703/Screenshot_2026-05-21_at_12.54.50_AM_tj5adq.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346703/Screenshot_2026-05-21_at_12.54.50_AM_tj5adq.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346705/Screenshot_2026-05-21_at_12.55.03_AM_nzsc8v.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346695/Screenshot_2026-05-21_at_12.55.34_AM_cvqtdw.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346697/Screenshot_2026-05-21_at_12.55.43_AM_anpr7l.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346697/Screenshot_2026-05-21_at_12.56.00_AM_eqatts.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346702/Screenshot_2026-05-21_at_12.56.09_AM_d8len4.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346703/Screenshot_2026-05-21_at_12.57.01_AM_viaw69.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346701/Screenshot_2026-05-21_at_12.57.16_AM_t8z7sf.png",
      "https://res.cloudinary.com/djnazqqgr/image/upload/v1779346706/Screenshot_2026-05-21_at_12.55.13_AM_qo8ymu.png",
    ],
    features: [
      "Server-side rendering with Next.js for SEO optimization",
      "Component-based architecture with React",
      "Type-safe development with TypeScript",
      "Dynamic project gallery with image optimization",
      "Interactive service area map integration",
      "Multi-step quote request form with validation",
      "Testimonial management system",
      "Responsive design system with Tailwind CSS",
      "Optimized image loading with Next.js Image",
    ],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    title: "GreenScape Pro",
    description:
      "Developed a server-rendered Next.js application with TypeScript for a Boulder County landscaping company, featuring dynamic project galleries, interactive service area mapping, and a streamlined quote request flow. Implemented React component architecture with Tailwind CSS for responsive design, utilized Next.js Image optimization for performance, and built a testimonial management system — showcasing expertise in modern React frameworks, TypeScript, and SEO-optimized web development.",
    category: "business",
    liveLink: "https://demo-greenscape.netlify.app/",
    codeLink: "https://github.com/zackaryzbrown/Greenscape-Demo",
  },
];

export default Items;
