import {
  RESUME_HEADER_LINKS,
  RESUME_SUMMARY,
  SITE_PROFILE,
} from "./SiteContent";

export const resumeData = {
  profile: {
    name: SITE_PROFILE.name,
    title: SITE_PROFILE.title,
    image: SITE_PROFILE.profileImage,
    links: RESUME_HEADER_LINKS,
  },
  summary: RESUME_SUMMARY,
  education: [
    {
      title: "University of Phoenix",
      subtitle: "Bachelor of Science in Computer Science",
      location: "Online",
      date: "Expected 2029",
    },
    {
      title: "Western Colorado University",
      subtitle: "Computer Science coursework",
      location: "Gunnison, CO",
      date: "August 2022 - March 2024",
    },
  ],
  featuredExperience: [
    {
      role: "ZBWebSolutions",
      companyLine:
        "Founder & Frontend Developer • Erie, CO • Aug 2025 - Present",
      projects: [
        {
          title: "A Child's Perspective",
          href: "https://achildsperspective.com/",
          ariaLabel: "Visit the A Child's Perspective website",
          ctaLabel: "View case study ->",
          date: "May 2026 - Present",
          type: "Client website",
          location: "Freelance",
          stack: ["React", "TypeScript", "Tailwind CSS", "Lighthouse"],
          bullets: [
            "Reworked a booking-focused client site with clearer page hierarchy, stronger call-to-action placement, and cleaner service flow for prospective parents.",
            "Raised accessibility and mobile usability through form UX improvements, semantic structure, and responsive navigation patterns.",
          ],
        },
        {
          title: "JustMalikBeats",
          href: "https://malikbeats.com",
          ariaLabel: "Visit the JustMalikBeats website",
          ctaLabel: "View case study ->",
          date: "October 2025 - January 2026",
          type: "Client commerce platform",
          location: "Freelance",
          stack: ["React", "Node.js", "MongoDB", "Stripe", "AWS Amplify"],
          bullets: [
            "Built a responsive digital-commerce frontend for an independent producer with clear discovery, preview, and checkout flows.",
            "Implemented account, storefront, and admin-facing experiences with authentication, secure payments, and maintainable UI architecture.",
          ],
        },
        {
          title: "MHKTraining",
          href: "https://mhktraining.com",
          ariaLabel: "Visit the MHKTraining (Mile High Karate) website",
          ctaLabel: "View case study ->",
          date: "August 2025 - October 2025",
          type: "Client training platform",
          location: "Freelance",
          stack: ["React", "Node.js", "Docker", "AWS"],
          bullets: [
            "Designed and built a responsive training platform for students, parents, and instructors with clearer access to schedules, forms, and member resources.",
            "Rebuilt core pages with improved information architecture, stronger mobile-first layouts, and better lead-capture pathways.",
          ],
        },
        {
          title: "My Personal Accountant",
          href: "https://github.com/zackaryzbrown/PersonalFinance",
          ariaLabel: "View source code for My Personal Accountant",
          ctaLabel: "View case study ->",
          date: "June 2025 - February 2026",
          type: "Personal product build",
          location: "Personal project",
          stack: ["Next.js", "React", "TypeScript", "PostgreSQL", "Prisma"],
          bullets: [
            "Rebuilt a local finance workflow into a web dashboard with persistent data, CSV import, and transaction analysis views.",
            "Developed budgeting and category-based reporting flows to surface spending trends and support monthly planning.",
          ],
        },
      ],
    },
  ],
  workExperience: [
    {
      title: "Automotive Technician & Team Trainer",
      company: "Firestone Complete Autocare",
      location: "Westminster, CO",
      date: "Mar 2024 - Jun 2026",
      type: "Full-time",
      bullets: [
        "Handled high-pressure diagnostics and team training with a focus on troubleshooting discipline, documentation, and reliable handoffs.",
      ],
    },
  ],
  selfDevelopment: [
    {
      title: "100Devs Training Program",
      location: "Remote",
      date: "November 2025 - Present",
      bullets: [
        "Continued frontend engineering practice through structured coursework, project work, and collaborative peer review.",
        "Actively participate in developer communities and technical discussions to sharpen implementation and communication skills.",
      ],
    },
    {
      title: "RFID Access-Control Prototype",
      location: "Independent Arduino project",
      date: "June 2026",
      href: "https://github.com/zackaryzbrown/RFID_DOORLOCK",
      ariaLabel: "View the RFID Access-Control Prototype source code on GitHub",
      ctaLabel: "View source code ->",
      bullets: [
        "Programmed an Arduino-based access system in C++ using an MFRC522 RFID reader, 16x2 I2C LCD, and servo-actuated lock.",
        "Implemented authorized-card validation, lock-state toggling, status feedback, and invalid-card handling, then integrated the electronics with custom 3D-printed mechanical parts.",
      ],
    },
    {
      title: "RoboRAVE SumoBot Team Captain",
      location: "Three-person competition team",
      date: "2017",
      bullets: [
        "Led a three-student team to second place in the SumoBot division at a regional RoboRAVE competition.",
        "Coordinated development while contributing sensor logic, motor control, autonomous strategy, chassis design, testing, and debugging.",
      ],
    },
    {
      title: "Network Infrastructure Exposure",
      location: "Data center and home networking",
      date: "Hands-on experience",
      bullets: [
        "Assisted with tracing and documenting network cable routes in a data-center environment using cable testers and crimping tools.",
        "Installed, terminated, and tested Ethernet cabling for a home network, including cable routing and endpoint connectivity.",
      ],
    },
  ],
  skills: [
    "React",
    "TypeScript",
    "JavaScript",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "Responsive Design",
    "Component Architecture",
    "Next.js",
    "Node.js",
    "Express",
    "REST APIs",
    "MongoDB",
    "PostgreSQL",
    "Auth/JWT",
    "Stripe",
    "AWS Amplify",
    "Vercel",
    "Netlify",
    "Cloudinary",
    "Git",
    "GitHub",
    "VS Code",
    "Vite",
    "Lighthouse",
    "Accessibility",
    "Performance Optimization",
    "Technical SEO",
    "Input Validation",
  ],
};
