import {
  RESUME_HEADER_LINKS,
  RESUME_SUMMARY,
  SITE_PROFILE,
} from "./SiteContent";

export const resumeData = {
  profile: {
    name: SITE_PROFILE.name,
    title: SITE_PROFILE.title,
    image: SITE_PROFILE.resumeImage,
    links: RESUME_HEADER_LINKS,
  },
  summary: RESUME_SUMMARY,
  education: [
    {
      title: "Front Range Community College",
      subtitle: "Associate of Science in Computer Science",
      location: "Westminster, CO",
      date: "Starting Aug 2026 (Expected May 2027)",
    },
    {
      title: "Western Colorado University",
      subtitle: "Some College in Computer Science",
      location: "Gunnison, CO",
      date: "August 2022 - March 2024",
    },
    {
      title: "Sandra Day O'Connor High School",
      subtitle: "High School in Computer Science",
      location: "Phoenix, AZ",
      date: "August 2018 - May 2022",
      bullets: ["AP Computer Science & Robotic Courses"],
    },
  ],
  featuredExperience: [
    {
      role: "ZBWebSolutions",
      companyLine:
        "Founder & Frontend Developer • Erie, CO • Aug 2025 - Present",
      projects: [
        {
          title: "A Child's Perspective",
          href: "https://achildsperspective.com/",
          ariaLabel: "Visit the A Child's Perspective website",
          ctaLabel: "View case study ->",
          date: "May 2026 - Present",
          type: "Client website",
          location: "Freelance",
          stack: ["React", "TypeScript", "Tailwind CSS", "Lighthouse"],
          bullets: [
            "Reworked a booking-focused client site with clearer page hierarchy, stronger call-to-action placement, and cleaner service flow for prospective parents.",
            "Raised accessibility and mobile usability through form UX improvements, semantic structure, and responsive navigation patterns.",
          ],
        },
        {
          title: "JustMalikBeats",
          href: "https://malikbeats.com",
          ariaLabel: "Visit the JustMalikBeats website",
          ctaLabel: "View case study ->",
          date: "October 2025 - January 2026",
          type: "Client commerce platform",
          location: "Freelance",
          stack: ["React", "Node.js", "MongoDB", "Stripe", "AWS Amplify"],
          bullets: [
            "Built a responsive digital-commerce frontend for an independent producer with clear discovery, preview, and checkout flows.",
            "Implemented account, storefront, and admin-facing experiences with authentication, secure payments, and maintainable UI architecture.",
          ],
        },
        {
          title: "MHKTraining",
          href: "https://mhktraining.com",
          ariaLabel: "Visit the MHKTraining (Mile High Karate) website",
          ctaLabel: "View case study ->",
          date: "August 2025 - October 2025",
          type: "Client training platform",
          location: "Freelance",
          stack: ["React", "Node.js", "Docker", "AWS"],
          bullets: [
            "Designed and built a responsive training platform for students, parents, and instructors with clearer access to schedules, forms, and member resources.",
            "Rebuilt core pages with improved information architecture, stronger mobile-first layouts, and better lead-capture pathways.",
          ],
        },
        {
          title: "The Futons",
          href: "https://thefutons.band/",
          ariaLabel: "Visit The Futons website",
          ctaLabel: "View case study ->",
          date: "June 2025 - August 2025",
          type: "Client promotional site",
          location: "Freelance",
          stack: ["HTML", "CSS", "JavaScript", "Cloudinary"],
          bullets: [
            "Shipped a performance-focused promotional site for a local band with responsive layouts and image-heavy content.",
            "Implemented lazy loading and progressive media delivery to improve page-load behavior on slower connections.",
          ],
        },
        {
          title: "My Personal Accountant",
          href: "https://github.com/zackaryzbrown/PersonalFinance",
          ariaLabel: "View source code for My Personal Accountant",
          ctaLabel: "View case study ->",
          date: "June 2025 - February 2026",
          type: "Personal product build",
          location: "Personal project",
          stack: ["Next.js", "React", "TypeScript", "PostgreSQL", "Prisma"],
          bullets: [
            "Rebuilt a local finance workflow into a web dashboard with persistent data, CSV import, and transaction analysis views.",
            "Developed budgeting and category-based reporting flows to surface spending trends and support monthly planning.",
          ],
        },
      ],
    },
  ],
  workExperience: [
    {
      title: "Automotive Technician & Team Trainer",
      company: "Firestone Complete Autocare",
      location: "Westminster, CO",
      date: "Mar 2024 - Jun 2026",
      type: "Full-time",
      bullets: [
        "Handled high-pressure diagnostics and team training with a focus on troubleshooting discipline, documentation, and reliable handoffs.",
      ],
    },
    {
      title: "Meat & Seafood Clerk / Courtesy Clerk",
      company: "Kroger",
      location: "Gunnison, CO",
      date: "May 2023 - Mar 2024",
      type: "Full-time",
      bullets: [
        "Maintained quality, safety, and customer-facing service standards while working quickly in high-traffic retail operations.",
      ],
    },
    {
      title: "Heavy Diesel Mechanic",
      company: "Par Five LLC",
      location: "Artesia, NM",
      date: "Jun 2022 - Jul 2022",
      type: "Part-time",
      compact: true,
      bullets: [
        "Performed repair and welding tasks on diesel equipment with attention to safety, precision, and reduced downtime.",
      ],
    },
    {
      title: "Maintenance Technician",
      company: "Firestone Complete Autocare",
      location: "Phoenix, AZ",
      date: "Aug 2021 - May 2022",
      type: "Full-time",
      compact: true,
      bullets: [
        "Supported preventive maintenance workflows and repeatable procedures to keep equipment dependable and service turnaround consistent.",
      ],
    },
    {
      title: "Lubrication Technician",
      company: "Fenney's Automotive",
      location: "Phoenix, AZ",
      date: "May 2021 - Aug 2021",
      type: "Full-time",
      compact: true,
      bullets: [
        "Completed routine service work with strong quality control, time management, and customer-facing communication.",
      ],
    },
    {
      title: "Facilities Maintenance Technician",
      company: "Best Western",
      location: "Artesia, NM",
      date: "May 2019 - August 2019",
      type: "Seasonal",
      compact: true,
      bullets: [
        "Resolved facility issues across departments with fast triage, practical fixes, and dependable follow-through.",
      ],
    },
    {
      title: "Office Assistant",
      company: "Chamber of Commerce",
      location: "Artesia, NM",
      date: "May 2018 - August 2018",
      type: "Seasonal",
      compact: true,
      bullets: [
        "Coordinated administrative tasks and information packets with strong organization, communication, and stakeholder support.",
      ],
    },
  ],
  selfDevelopment: [
    {
      title: "100Devs Training Program",
      location: "Remote",
      date: "November 2025 - Present",
      bullets: [
        "Continued frontend engineering practice through structured coursework, project work, and collaborative peer review.",
        "Actively participate in developer communities and technical discussions to sharpen implementation and communication skills.",
      ],
    },
    {
      title: "Personal Frontend Product Labs",
      location: "Independent",
      date: "2025 - Present",
      bullets: [
        "Built browser-based tools and product experiments to practice UI architecture, state management, and interaction design.",
      ],
    },
  ],
  certifications: [
    {
      type: "certificate",
      title: "EPA 609 Certification",
      issuer: "ESCO Institute",
      detail: "Issued: April 25, 2025",
    },
    {
      type: "award",
      title: "Area Top Performer (Multiple Quarters)",
      issuer: "Firestone Complete Autocare",
      detail: "Dec 2022, Dec 2024, Apr 2025, Aug 2025, Apr 2026",
    },
  ],
  skills: [
    "React",
    "TypeScript",
    "JavaScript",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "Responsive Design",
    "Component Architecture",
    "Next.js",
    "Node.js",
    "Express",
    "REST APIs",
    "MongoDB",
    "PostgreSQL",
    "Auth/JWT",
    "Stripe",
    "AWS Amplify",
    "Vercel",
    "Netlify",
    "Cloudinary",
    "Git",
    "GitHub",
    "VS Code",
    "Vite",
    "Lighthouse",
    "Accessibility",
    "Performance Optimization",
    "Technical SEO",
    "Input Validation",
  ],
};
